package com.karumien.hris.openapi.server.controller;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import com.karumien.hris.openapi.server.service.KafkaIntegrationService;


@SpringBootTest
@AutoConfigureMockMvc
class ReplacerControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    KafkaIntegrationService kafkaIntegrationService;

    @Test
    void replace() throws Exception {
        this.mockMvc.perform(get("/custom").contentType(MediaType.APPLICATION_JSON).content(getJsonRequest()))
                .andExpect(status().isOk()).andExpect(content().json(getJsonResponse()));
    }

    private String getJsonRequest() {
        return "{\n"
                + "    \"fullName\": \"Ivo Šmajstrla\",\n"
                + "    \"displayName\": \"Ivo Šmajstrla\",\n"
                + "    \"personal\": {\n"
                + "        \"shortBirthDate\": \"01-01\",\n"
                + "        \"pronouns\": \"Xe / Xem\",\n"
                + "        \"communication\": {\n"
                + "            \"skypeUsername\": null,\n"
                + "            \"slackUsername\": null\n"
                + "        },\n"
                + "        \"custom\": {\n"
                + "            \"field_1620721757321\": [],\n"
                + "            \"field_1620656620397\": null,\n"
                + "            \"field_1620656651374\": null,\n"
                + "            \"field_1620656641418\": null,\n"
                + "            \"field_1620656719091\": null\n"
                + "        },\n"
                + "        \"honorific\": null,\n"
                + "        \"nationality\": [\n"
                + "            \"Andorran\"\n"
                + "        ]\n"
                + "    },\n"
                + "    \"creationDateTime\": \"2021-05-10T09:29:06.358057\",\n"
                + "    \"work\": {\n"
                + "        \"shortStartDate\": \"05-01\",\n"
                + "        \"startDate\": \"2021-05-01\",\n"
                + "        \"manager\": null,\n"
                + "        \"workPhone\": null,\n"
                + "        \"tenureDuration\": {\n"
                + "            \"periodISO\": \"P5M\",\n"
                + "            \"sortFactor\": 150,\n"
                + "            \"humanize\": \"5 months\"\n"
                + "        },\n"
                + "        \"durationOfEmployment\": {\n"
                + "            \"periodISO\": \"P5M\",\n"
                + "            \"sortFactor\": 150,\n"
                + "            \"humanize\": \"5 months\"\n"
                + "        },\n"
                + "        \"reportsToIdInCompany\": null,\n"
                + "        \"employeeIdInCompany\": null,\n"
                + "        \"reportsTo\": null,\n"
                + "        \"workMobile\": \"2425346374\",\n"
                + "        \"indirectReports\": 1,\n"
                + "        \"siteId\": 1482762,\n"
                + "        \"department\": \"Test\",\n"
                + "        \"tenureYears\": 0,\n"
                + "        \"customColumns\": {\n"
                + "            \"column_1620832556726\": null,\n"
                + "            \"column_1620832454233\": null,\n"
                + "            \"column_1621859812592\": null,\n"
                + "            \"column_1620832033458\": null,\n"
                + "            \"column_1620832653579\": null,\n"
                + "            \"column_1620832080748\": null,\n"
                + "            \"column_1621536524514\": null,\n"
                + "            \"column_1622629726113\": [],\n"
                + "            \"column_1620847674358\": null,\n"
                + "            \"column_1620847694365\": null,\n"
                + "            \"column_1620832362165\": \"CTO\",\n"
                + "            \"column_1620847706988\": null,\n"
                + "            \"column_1620843628717\": null,\n"
                + "            \"column_1620847723325\": null\n"
                + "        },\n"
                + "        \"isManager\": true,\n"
                + "        \"title\": \"Admins\",\n"
                + "        \"site\": \"London (Demo)\",\n"
                + "        \"activeEffectiveDate\": \"2021-05-02\",\n"
                + "        \"directReports\": 1,\n"
                + "        \"secondLevelManager\": null,\n"
                + "        \"daysOfPreviousService\": 0,\n"
                + "        \"yearsOfService\": 0.416\n"
                + "    },\n"
                + "    \"avatarUrl\": \"https://cdn.filestackcontent"
                + ".com/ZyBWbFNPR5GVBVULggFB?policy"
                + "=eyJoYW5kbGUiOiJaeUJXYkZOUFI1R1ZCVlVMZ2dGQiIsImV4cGlyeSI6NDYzNTkxODcwNCwiY2FsbCI6WyJyZWFkIiwgImNvbnZlcnQiXX0=&signature"
                + "=b96b1f5caae283ec9d7ac9ea74a66b2752b372128690017ba586483fd1f0acc5\",\n"
                + "    \"secondName\": null,\n"
                + "    \"about\": {\n"
                + "        \"foodPreferences\": [\n"
                + "            \"meatarian\"\n"
                + "        ],\n"
                + "        \"custom\": {\n"
                + "            \"field_1620723273420\": null\n"
                + "        },\n"
                + "        \"socialData\": {\n"
                + "            \"linkedin\": null,\n"
                + "            \"twitter\": null,\n"
                + "            \"facebook\": null\n"
                + "        },\n"
                + "        \"superpowers\": [\n"
                + "            \"thinking\"\n"
                + "        ],\n"
                + "        \"hobbies\": [\n"
                + "            \"sleeping\"\n"
                + "        ],\n"
                + "        \"about\": null,\n"
                + "        \"avatar\": \"https://cdn.filestackcontent"
                + ".com/ZyBWbFNPR5GVBVULggFB?policy"
                + "=eyJoYW5kbGUiOiJaeUJXYkZOUFI1R1ZCVlVMZ2dGQiIsImV4cGlyeSI6NDYzNTkxODcwNCwiY2FsbCI6WyJyZWFkIiwgImNvbnZlcnQiXX0=&signature"
                + "=b96b1f5caae283ec9d7ac9ea74a66b2752b372128690017ba586483fd1f0acc5\"\n"
                + "    },\n"
                + "    \"companyId\": 393237,\n"
                + "    \"email\": \"ismajstrla@gmail.com\",\n"
                + "    \"surname\": \"Šmajstrla\",\n"
                + "    \"id\": \"2570428242561335380\",\n"
                + "    \"firstName\": \"Ivo\"\n"
                + "}";
    }

    private String getJsonResponse() {
        return "{\n"
                + "    \"fullName\": null,\n"
                + "    \"displayName\": \"Ivo Šmajstrla\",\n"
                + "    \"personal\": {\n"
                + "        \"shortBirthDate\": \"01-01\",\n"
                + "        \"pronouns\": \"Xe / Xem\",\n"
                + "        \"communication\": {\n"
                + "            \"skypeUsername\": null,\n"
                + "            \"slackUsername\": null\n"
                + "        },\n"
                + "        \"citizenship\": [],\n"
                + "        \"birthSurname\": null,\n"
                + "        \"countryOfBirth\": null,\n"
                + "        \"cityOfBirth\": null,\n"
                + "        \"birthNumber\": null,\n"
                + "        \"honorific\": null,\n"
                + "        \"nationality\": [\n"
                + "            \"Andorran\"\n"
                + "        ]\n"
                + "    },\n"
                + "    \"creationDateTime\": \"2021-05-10T09:29:06.358057\",\n"
                + "    \"work\": {\n"
                + "        \"shortStartDate\": \"05-01\",\n"
                + "        \"startDate\": \"2021-05-01\",\n"
                + "        \"manager\": null,\n"
                + "        \"workPhone\": null,\n"
                + "        \"tenureDuration\": {\n"
                + "            \"periodISO\": \"P5M\",\n"
                + "            \"sortFactor\": 150,\n"
                + "            \"humanize\": \"5 months\"\n"
                + "        },\n"
                + "        \"durationOfEmployment\": {\n"
                + "            \"periodISO\": \"P5M\",\n"
                + "            \"sortFactor\": 150,\n"
                + "            \"humanize\": \"5 months\"\n"
                + "        },\n"
                + "        \"reportsToIdInCompany\": null,\n"
                + "        \"employeeIdInCompany\": null,\n"
                + "        \"reportsTo\": null,\n"
                + "        \"workMobile\": \"2425346374\",\n"
                + "        \"indirectReports\": 1,\n"
                + "        \"siteId\": 1482762,\n"
                + "        \"department\": \"Test\",\n"
                + "        \"tenureYears\": 0,\n"
                + "        \"businessUnitId\": null,\n"
                + "        \"note\": null,\n"
                + "        \"reason\": null,\n"
                + "        \"budgetId\": null,\n"
                + "        \"profitAndCostCenterId\": null,\n"
                + "        \"legalEntity\": null,\n"
                + "        \"costCenterCost\": null,\n"
                + "        \"adRole\": [],\n"
                + "        \"dottedLineManager\": null,\n"
                + "        \"hrBusinessPartner\": null,\n"
                + "        \"businessUnitOrFunction\": \"CTO\",\n"
                + "        \"hrGeneralist\": null,\n"
                + "        \"customSecondLevelManager\": null,\n"
                + "        \"payrollSpecialist\": null,\n"
                + "        \"isManager\": true,\n"
                + "        \"title\": \"Admins\",\n"
                + "        \"site\": \"London (Demo)\",\n"
                + "        \"activeEffectiveDate\": \"2021-05-02\",\n"
                + "        \"directReports\": 1,\n"
                + "        \"secondLevelManager\": null,\n"
                + "        \"daysOfPreviousService\": 0,\n"
                + "        \"yearsOfService\": 0.416\n"
                + "    },\n"
                + "    \"avatarUrl\": \"https://cdn.filestackcontent"
                + ".com/ZyBWbFNPR5GVBVULggFB?policy"
                + "=eyJoYW5kbGUiOiJaeUJXYkZOUFI1R1ZCVlVMZ2dGQiIsImV4cGlyeSI6NDYzNTkxODcwNCwiY2FsbCI6WyJyZWFkIiwgImNvbnZlcnQiXX0=&signature"
                + "=b96b1f5caae283ec9d7ac9ea74a66b2752b372128690017ba586483fd1f0acc5\",\n"
                + "    \"secondName\": null,\n"
                + "    \"about\": {\n"
                + "        \"foodPreferences\": [\n"
                + "            \"meatarian\"\n"
                + "        ],\n"
                + "        \"favoriteSnack\": null,\n"
                + "        \"socialData\": {\n"
                + "            \"linkedin\": null,\n"
                + "            \"twitter\": null,\n"
                + "            \"facebook\": null\n"
                + "        },\n"
                + "        \"superpowers\": [\n"
                + "            \"thinking\"\n"
                + "        ],\n"
                + "        \"hobbies\": [\n"
                + "            \"sleeping\"\n"
                + "        ],\n"
                + "        \"about\": null,\n"
                + "        \"avatar\": \"https://cdn.filestackcontent"
                + ".com/ZyBWbFNPR5GVBVULggFB?policy"
                + "=eyJoYW5kbGUiOiJaeUJXYkZOUFI1R1ZCVlVMZ2dGQiIsImV4cGlyeSI6NDYzNTkxODcwNCwiY2FsbCI6WyJyZWFkIiwgImNvbnZlcnQiXX0=&signature"
                + "=b96b1f5caae283ec9d7ac9ea74a66b2752b372128690017ba586483fd1f0acc5\"\n"
                + "    },\n"
                + "    \"companyId\": 393237,\n"
                + "    \"email\": \"ismajstrla@gmail.com\",\n"
                + "    \"surname\": \"Šmajstrla\",\n"
                + "    \"id\": \"2570428242561335380\",\n"
                + "    \"firstName\": \"Ivo\"\n"
                + "}";
    }
}